name: "Manual Action"
on:
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: on

jobs:
  hello:
    name: Hello
    # runs-on: codebuild-custom-rust-runner-${{ github.run_id }}-${{ github.run_attempt }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: BurntSushi/ripgrep

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - name: Configure sccache
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
      #       core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          # RUSTC_WRAPPER=/usr/local/bin/sccache cargo build --release
          cargo build --release
