name: "Manual Action"
on:
  workflow_dispatch:

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compose up
        run: docker compose up -d

      - name: wait
        run: sleep 5

      - name: check
        run: ping -c 3 sub.localhost
