name: "Manual Action"
on:
  workflow_dispatch:

jobs:
  hello:
    name: Hello
    runs-on:
      - codebuild-github-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: hello
        run: echo "Hello self-hosted runner!"
