name: "Manual Action"
on:
  workflow_dispatch:

jobs:
  hello:
    name: Hello
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: yoshihitoh/ut-cli

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.86.0

      - name: Build
        run: cargo build --release
