name: "Manual Action"
on: [workflow_dispatch]
jobs:
  hello:
    name: Hello
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Hello
        uses: ./.github/actions/hello
        with:
          message: "This is a conditional message!!"
