name: "Manual Action"
on:
  workflow_dispatch:

jobs:
  hello:
    name: Hello
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: hello
        run: echo "Hello self-hosted runner!"
